name: dynamic_form_builder
description: A Flutter package to create forms dynamically.
version: 0.0.2
repository: https://github.com/naeemeltaief/dynamic_form_builder.git
homepage: https://github.com/naeemeltaief/dynamic_form_builder.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  intl: ^0.19.0
  file_picker: ^8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true